name: Images
on:
  push:
    branches: [master]

jobs:
  build-and-push:
    name: Build and push all images
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        include:
          - name: maker-image

          - name: tester-image

          - name: kube-test-image

          - name: compilers-image

          - name: bpftool-image

          - name: iproute2-image

          - name: llvm-image

          - name: startup-script-image

          - name: ca-certificates-image

          - name: checkpatch-image
    steps:
      - uses: actions/checkout@v1
      - uses: docker://docker.io/cilium/image-maker:8fb8f8325d966505552183f756eae4e3cb60d195
        name: Register binfmt from multi-platform builds
        with:
          entrypoint: docker
          args: run --privileged linuxkit/binfmt:5d33e7346e79f9c13a73c6952669e47a53b063d4 
      - uses: docker://docker.io/cilium/image-maker:8fb8f8325d966505552183f756eae4e3cb60d195
        name: Run make lint
        with:
          entrypoint: make
          args: lint
      - uses: docker://docker.io/cilium/image-maker:8fb8f8325d966505552183f756eae4e3cb60d195
        name: Run make ${{ matrix.name }}
        env:
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD_CI }}
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME_CI }}
          QUAY_PASSWORD: ${{ secrets.QUAY_PASSOWRD_IMAGE_TOOLS }}
          QUAY_USERNAME: ${{ secrets.QUAY_USERNAME_IMAGE_TOOLS }}
        with:
          entrypoint: make
          args: ${{ matrix.name }} PUSH=true
